### ISSUE TITLE
sass is no longer available from CRAN

### ISSUE THREAD

**Issue by vincentarelbundock** [rstudio/sass#22]
https://cran.r-project.org/web/packages/sass/index.html

```
Package ‘sass’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2019-07-20 as installation errors were not corrected in time.
```

This poses problems for packages which use `sass` as a dependency (for example `gt`).

**Comment by rich-iannone** [comment]
The **sass** package will need to be resubmitted to CRAN (after fixing the problems that caused its removal). In the meantime, I'll have to modify the DESCRIPTION file to put **sass** in the Remotes list.

**Comment by yihui** [comment]
@rich-iannone When do you plan to resubmit? FYI, CRAN submission will be closed soon for ten days. Without **sass** on CRAN, I'll have problems with **knitr**'s future submissions (and I plan to do a new release relatively soon) because **knitr** Suggests **sass**, and it won't pass R CMD check now:

```
 using log directory 'd:/RCompile/CRANguest/R-devel/knitr.Rcheck'
* using R Under development (unstable) (2019-07-05 r76784)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'knitr/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'knitr' version '1.23.4'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE

Suggests or Enhances not in mainstream repositories:
  sass
```

I don't know what the problem that CRAN requested you to fix, but when I receive emails from CRAN, I usually give them the highest priority.

**Comment by jcheng5** [comment]
@yihui Yikes, I didn't know anyone had a dependency on sass. I've taken over maintainership, and I believe I can submit to CRAN later today.

**Comment by yihui** [comment]
@jcheng5 No hurry now. I used a dirty trick in **knitr** to remove the Suggests dependency and submitted a new version of **knitr** to CRAN. When **sass** goes back to CRAN, I'll get rid of the trick. Thanks!

**Comment by jcheng5** [comment]
@yihui Sounds good. I just submitted but it's quite possible we'll have to resubmit if the Solaris issues persist; so probably a smart call on your part.
