### ISSUE TITLE
Unable to load sass

### ISSUE THREAD

**Issue by Waschoi** [rstudio/sass#23]
Because I am behind a firewall I downloaded the zip from github and installed sass using:
devtools::install_local("C:/Users/XXX/Downloads/sass-master.zip", dependencies = T, force = T)

install went through, but I am unable too load the package:

`
make[1]: Leaving directory '/cygdrive/c/Users/XXXX~1/AppData/Local/Temp/Rtmpy0v8ag/remotes22e47a71d42/sass-master/src-x64/libsass'
C:/RBuildTools/3.5/mingw_64/bin/gcc -shared -s -static-libgcc -o sass.dll tmp.def compile.o init.o ./libsass/lib/libsass.a -lstdc++ -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
installing to \\XXXX/XXXXX$/Home/UserXXXX/Eigene Dateien/R/win-library/3.5/sass/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'sass'
    finding HTML links ... fertig
    as_sass                                 html  
    sass                                    html  
    sass_cache_options                      html  
    sass_import                             html  
    sass_options                            html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (sass)
In R CMD INSTALL
> library(saas)
Error in library(saas) : there is no package called ‘saas’`

Thanks in advance

**Comment by rich-iannone** [comment]
It looks like the installation was successful but you misspelled `sass`. Could you try again with `library(sass)`?

**Comment by Waschoi** [comment]
I'm so sorry. That was totally stupid of me. 
But still: when using the gt package (therefore I need sass), I get: Error in sass::sass_file(system_file(file = "css/gt_colors.scss")). So there seems to be something wrong

**Comment by Waschoi** [comment]
The reason was probably that my library was on a network drive. Now it works.
