### ISSUE TITLE
sass_file() should be properly vectorized (to improve performance)

### ISSUE THREAD

**Issue by cpsievert** [rstudio/sass#49]
It currently (sort of) works with a warning because `file.exists()` is not vectorized, but everything else is:

```r
sass::sass_file <- function (input) {
    if (!file.exists(input)) {
        stop("Could not find file: '", input, "' in dir: ", getwd())
    }
    input <- normalizePath(input, mustWork = TRUE)
    ret <- sass_import(input)
    class(ret) <- c("sass_file", class(ret))
    attr(ret, "sass_file_path") <- input
    ret
}
```

Turns out `normalizePath()` can be slow, so we should try to speed this with vectorization

**Comment by wch** [comment]
Closing because after profiling real use cases, the time for `sass_file` is essentially nothing, compared to other bottlenecks.
