### ISSUE TITLE
Using in shiny as dynamic input: inefficiency of constnatly adding more style tags to the page

### ISSUE THREAD

**Issue by daattali** [rstudio/sass#65]
In the basic vignette, there's a section about using sass for dynamically inserting css into an app. The approach used results in new HTML tags being added to the DOM every time the input changes. In the example given, the tag is short so it's not too important, but I can imagine people who build large apps and insert hundreds of lines of css would see this example and replicate it, and end up in situations where thousands of lines of HTML are being added to their page. 

I'm not sure it's a great practice to recommend in an official RStudio package

**Comment by jdtrat** [comment]
Hi Dean! Based on our recent discussion about this, here's a possible solution using `removeUI()`:

```r
library(shiny)

ui <- fluidPage(
  headerPanel("Sass Color Example"),
  colourpicker::colourInput("color", "Background Color", value = "#6498d2", showColour = "text"),
  uiOutput("sass")
)

server <- function(input, output) {
  output$sass <- renderUI({
    tags$head(tags$style(id = "background_color", css()))
  })
  css <- reactive({
    shiny::removeUI(selector = "#background_color", immediate = TRUE)
    sass::sass(list(
      list(color = input$color),
      "body { background-color: $color; }"
    ))
  })
}

shinyApp(ui, server)
```
There is a noticeable delay with this implementation, though. In the attachment, you will see the UI go between the original and new styles separated by the default (no style tags), though it doesn't always seem to happen (not sure why). Maybe this could be solved by using a reactive value to keep track of the style tag and then you remove the old one? Part of that might look like this:

```r
tag_id <- reactiveVal(1)
 output$sass <- renderUI({
    tags$head(tags$style(id = paste0("background_color_", tag_id()), css()))
  })
```

What do you think?


https://user-images.githubusercontent.com/51417262/103244061-c9058100-4929-11eb-9b60-afbd63c1dbd4.mp4

**Comment by daattali** [comment]
I just tested the code, and yes there is a slight delay between selecting a colour and seeing it as the background. However, that delay exists in the version in the vignette as well, and will always exist in shiny due to the round trip of js -> shiny -> js.

I generally try to avoid side effects in reactives (removeUI is a side effect), so I personally would explore maybe something like 

```
library(shiny)

ui <- fluidPage(
  headerPanel("Sass Color Example"),
  colourpicker::colourInput("color", "Background Color", value = "#6498d2", showColour = "text")
)

server <- function(input, output) {
  observeEvent(input$color, {
    shiny::removeUI(selector = "#background_color")
    shiny::insertUI(
      selector = "head",
      where = "beforeEnd", 
      ui = tags$style(id = "background_color", paste("body { background-color:", input$color, "}"))
    )
  })
}

shinyApp(ui, server)
```

It has the added benefit that there's consistency in the API used - removeUI and insertUI, as opposed to removeUI with uiOutput

**Comment by jdtrat** [comment]
Thanks for clarifying why the delay occurs! Two questions/thoughts: 

1. Why would you recommend against using side effects in reactive?
2. When removing the style tag and inserting it again, the brief delay for a background color (which reverts to the default white) does not particularly matter. But when you have hundreds of lines of CSS, you essentially see the whole webpage reload. Not coming from a web-development background, I'm not sure why it's inefficient to add tags. I'm guessing it might slow down the web page? From a user-perspective, I would rather avoid seeing that CSS "reload." Perhaps only removing tags after a delay, so the first one would only be removed if a third is added, and the second would be removed if a fourth is added. That limits the style tags in the DOM and prevents the user from seeing a CSS reload. What do you think?

**Comment by daattali** [comment]
1. That's a big topic that has been answered better by others, I suggest
looking for discussions about it on the community forum or watching Joe
Cheng's videos on reactivity from the Shiny Developer Conference to
understand. It will almost never have an effect on your app but it is a
major and common anti pattern
2. I see your point, I can believe that with 100 rules there may be a
noticeable reload time. Maybe I'd add the new rules and then remove the old
ones instead of doing it the other way around then. Creating lots of unused
tags and having lots of repetitive unused CSS is unlikely to affect
performance in modern browsers, but it still is ugly and not ideal. I
haven't explored this much myself as I haven't run into a use case yet, I
just wanted to raise this as a potential issue

**Comment by jdtrat** [comment]
1. I will look into those resources, thanks!
2. I modified your solution so there is not visual delay -- i.e. the old tag is only removed once the new tag is added. It also works when using the reactive css object described in the vignette. 

```r
library(shiny)

ui <- fluidPage(
  headerPanel("Sass Color Example"),
  colourpicker::colourInput("color", "Background Color", value = "#6498d2", showColour = "text")
)

server <- function(input, output) {
  num_tag <- reactiveVal(0)
  
  observeEvent(input$color, {
    num_tag(num_tag() + 1)
    shiny::insertUI(
      selector = "head",
      where = "beforeEnd", 
      ui = tags$style(id = paste0("background_color_", num_tag()), 
                      paste("body { background-color:", input$color, "}"))
    )
      shiny::removeUI(selector = paste0("#background_color_", (num_tag() - 1)))
    
  })
}

shinyApp(ui, server)
```
https://user-images.githubusercontent.com/51417262/103432284-a6ce6600-4baa-11eb-8e97-a6c45aa2dabb.mp4
